version: '3'

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
      args:
        user: fernando
        uid: 1000
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
      - '${HOST_MACHINE_SECURE_HOST_PORT}:443'
    links:
      - database
    volumes:
      - ${DOCUMENT_ROOT-./app}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: 'client_host=host.docker.internal remote_port=${XDEBUG_PORT}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default_network

  database:
    build:
      context: './bin/${DATABASE}'
    container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
    restart: 'always'
    ports:
      - '127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306'
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default_network

  phpmyadmin:
    build:
      context: './bin/phpmyadmin'
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: '${HOST_MACHINE_MYSQL_PORT}-3306'
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes:
      - ./data/phpmyadmin/sessions:/sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
      - database
    networks:
      - default_network

  redis:
    build:
      context: './bin/redis'
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    ports:
      - '127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379'
    volumes:
      - ${REDIS_DATA_DIR-./data/redis}:/data
    depends_on:
      - webserver
    networks:
      - default_network

  memcached:
    build:
      context: './bin/memcached'
    container_name: '${COMPOSE_PROJECT_NAME}-memcached'
    ports:
      - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
    depends_on:
      - webserver
    networks:
      - default_network

  mailhog:
    build:
      context: './bin/mailhog'
    container_name: '${COMPOSE_PROJECT_NAME}-mailhog'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    depends_on:
      - webserver
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
